build.gradle.kts
src/main/java/team/startup/expo/ExpoApplication.java
src/main/java/team/startup/expo/domain/user/User.java
src/main/java/team/startup/expo/domain/user/exception/NotFoundUserException.java
src/main/java/team/startup/expo/domain/user/repository/UserRepository.java
src/main/java/team/startup/expo/global/auth/AuthDetails.java
src/main/java/team/startup/expo/global/auth/AuthDetailsService.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/exception/ErrorResponse.java
src/main/java/team/startup/expo/global/exception/GlobalException.java
src/main/java/team/startup/expo/global/exception/GlobalExceptionHandler.java
src/main/java/team/startup/expo/global/filter/ExceptionFilter.java
src/main/java/team/startup/expo/global/filter/JwtFilter.java
src/main/java/team/startup/expo/global/filter/RequestLogFilter.java
src/main/java/team/startup/expo/global/security/config/JwtSecurityConfig.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java
src/main/java/team/startup/expo/global/security/exception/ExpiredTokenException.java
src/main/java/team/startup/expo/global/security/exception/InvalidTokenException.java
src/main/java/team/startup/expo/global/security/handler/JwtAccessDeniedHandler.java
src/main/java/team/startup/expo/global/security/handler/JwtAuthenticationEntryPoint.java
src/main/java/team/startup/expo/global/security/jwt/JwtProperties.java
src/main/java/team/startup/expo/global/security/jwt/JwtProvider.java
src/main/java/team/startup/expo/global/security/jwt/TokenParser.java
src/main/resources/application.properties
src/main/resources/application.yml

프로젝트 시큐리티 기본 세팅과 요청, 에러 로그 필터를 추가하였습니다
Resolves: #3 
* 시큐리티 기본 세팅
* User 엔티티 임시 추가
* UserRepository 임시 추가

🔀 :: 시큐리티 기본 세팅

---

build.gradle.kts
src/main/java/team/startup/expo/domain/admin/Admin.java
src/main/java/team/startup/expo/domain/admin/repository/AdminRepository.java
src/main/java/team/startup/expo/domain/auth/exception/DuplicateNicknameException.java
src/main/java/team/startup/expo/domain/auth/exception/DuplicatePhoneNumberException.java
src/main/java/team/startup/expo/domain/auth/exception/NotFoundSmsAuthException.java
src/main/java/team/startup/expo/domain/auth/exception/NotVerificationSmsException.java
src/main/java/team/startup/expo/domain/auth/presentation/AuthController.java
src/main/java/team/startup/expo/domain/auth/presentation/dto/request/SignUpRequest.java
src/main/java/team/startup/expo/domain/auth/presentation/dto/request/SignUpRequestDto.java
src/main/java/team/startup/expo/domain/auth/service/SignUpService.java
src/main/java/team/startup/expo/domain/auth/service/impl/SignUpServiceImpl.java
src/main/java/team/startup/expo/domain/sms/SmsAuthEntity.java
src/main/java/team/startup/expo/domain/sms/repository/SmsAuthRepository.java
src/main/java/team/startup/expo/global/annotation/ReadOnlyTransactionService.java
src/main/java/team/startup/expo/global/annotation/TransactionService.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/redis/RedisConfig.java

서비스를 이용하기 위해 관리자의 회원가입을 추가하였습니다
Resolves: #9 
* signUp api 추가
* SmsAuthEntity로 sms 인증을 완료했는지 검증

🔀 :: 관리자 회원가입

---

src/main/java/team/startup/expo/domain/sms/SmsAuthEntity.java
src/main/java/team/startup/expo/domain/sms/exception/NotMatchRandomCodeException.java
src/main/java/team/startup/expo/domain/sms/presentation/SmsController.java
src/main/java/team/startup/expo/domain/sms/presentation/dto/request/VerifySmsRequestDto.java
src/main/java/team/startup/expo/domain/sms/service/VerifySmsService.java
src/main/java/team/startup/expo/domain/sms/service/impl/VerifySmsServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

sms 인증번호를 입력하여 올바른지 검사하는 api를 추가하였습니다.
Resolves: #13 
* verifySms api 추가

🔀 :: sms 인증번호 확인

---

src/main/java/team/startup/expo/domain/admin/presentation/AdminController.java
src/main/java/team/startup/expo/domain/admin/presentation/dto/request/AcceptAdminRequestDto.java
src/main/java/team/startup/expo/domain/admin/service/AcceptAdminService.java
src/main/java/team/startup/expo/domain/admin/service/impl/AcceptAdminServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

관리자가 회원가입을 하게 되면 PENDING으로 들어가는데 이것을 다른 관리자가 수락할 수 있는 api를 추가하였습니다
Resolves: #15 
* AcceptAdmin api 추가
로그인을 만들지 않아 테스트를 permitAll로 하여 나중에 로그인을 만들고 JWT로 따로 테스트 진행해야될 것 같습니다

🔀 :: PENDING 관리자 수락

---

src/main/java/team/startup/expo/domain/admin/repository/AdminRepository.java
src/main/java/team/startup/expo/domain/auth/exception/AdminStatePendingException.java
src/main/java/team/startup/expo/domain/auth/exception/DuplicateEmailException.java
src/main/java/team/startup/expo/domain/auth/exception/NotMatchPasswordException.java
src/main/java/team/startup/expo/domain/auth/presentation/AuthController.java
src/main/java/team/startup/expo/domain/auth/presentation/dto/request/SignInRequestDto.java
src/main/java/team/startup/expo/domain/auth/presentation/dto/response/TokenResponseDto.java
src/main/java/team/startup/expo/domain/auth/repository/RefreshTokenRepository.java
src/main/java/team/startup/expo/domain/auth/service/SignInService.java
src/main/java/team/startup/expo/domain/auth/service/impl/SignInServiceImpl.java
src/main/java/team/startup/expo/domain/auth/service/impl/SignUpServiceImpl.java
src/main/java/team/startup/expo/global/auth/AuthDetails.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/jackson/JacksonConfig.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java
src/main/java/team/startup/expo/global/security/jwt/JwtProvider.java
src/main/java/team/startup/expo/global/util/count/RefreshToken.java

관리자가 로그인 api를 추가하였습니다
Resolves: #17 
* signIn api 추가
* signUp api 로직에 email 존재 유무 체크 추가
로그인 api 테스트 진행하며 전에 테스트 하지 못 했던 #16 를 테스트 진행 후 아무 문제 없는 것을 확인하였습니다

🔀 :: 관리자 로그인 

---

src/main/java/team/startup/expo/domain/auth/presentation/AuthController.java
src/main/java/team/startup/expo/domain/auth/repository/RefreshTokenRepository.java
src/main/java/team/startup/expo/domain/auth/service/ReissueTokenService.java
src/main/java/team/startup/expo/domain/auth/service/impl/ReissueTokenServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

토큰을 재발급 할 수 있는 api를 추가하였습니다
Resolves: #19 
* ReissueToken api 추가

🔀 :: 토큰 재발급

---

src/main/java/team/startup/expo/domain/admin/util/UserUtil.java
src/main/java/team/startup/expo/domain/auth/presentation/AuthController.java
src/main/java/team/startup/expo/domain/auth/service/LogoutService.java
src/main/java/team/startup/expo/domain/auth/service/impl/LogoutServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

관리자 로그아웃을 추가하였습니다
Resolves: #21 
* Logout api 추가

🔀 :: 관리자 로그아웃

---

src/main/java/team/startup/expo/domain/admin/presentation/AdminController.java
src/main/java/team/startup/expo/domain/admin/presentation/dto/response/GetPendingAdminResponseDto.java
src/main/java/team/startup/expo/domain/admin/repository/AdminRepository.java
src/main/java/team/startup/expo/domain/admin/service/GetPendingAdminsService.java
src/main/java/team/startup/expo/domain/admin/service/impl/GetPendingAdminsServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

보류 중인 관리자 리스트를 불러오는 api를 추가하였습니다
Resolves: #23 
* getPendingAdmins api 추가

🔀 :: 보류 중인 관리자 리스트

---

src/main/java/team/startup/expo/domain/admin/presentation/AdminController.java
src/main/java/team/startup/expo/domain/admin/service/WithdrawalAdminService.java
src/main/java/team/startup/expo/domain/admin/service/impl/WithdrawalAdminServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

서비스 탈퇴 api를 추가하였습니다
Resolves: #25 
* withdrawalAdmin api 추가

🔀 :: 서비스 탈퇴

---

src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/standard/StandardProgramUser.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java
src/main/java/team/startup/expo/domain/training/TrainingProgram.java

erd가 변경되어 엔티티의 연관관계를 수정하였습니다
Resolves: #28 
* 여러 엔티티 연관관계 수정

🔀 :: 엔티티 연관관계 수정

---

src/main/java/team/startup/expo/domain/trainee/presentation/TraineeController.java
src/main/java/team/startup/expo/domain/trainee/presentation/dto/response/GetTraineeInformationResponseDto.java
src/main/java/team/startup/expo/domain/trainee/presentation/dto/response/GetTrainingProgramResponseDto.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java
src/main/java/team/startup/expo/domain/trainee/service/GetTrainingInformationService.java
src/main/java/team/startup/expo/domain/trainee/service/impl/GetTrainingInformationServiceImpl.java
src/main/java/team/startup/expo/domain/training/repository/TrainingProgramUserRepository.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

교원연수자 정보를 리스트로 불러올 수 있도록 추가하였습니다.
Resolves: #27 
* GetTraineeInformation api 추가
N + 1 문제가 일어날 가능성이 높아 나중에 성능최적화가 필요할 것 같습니다.

🔀 :: 교원연수자 정보 리스트

---

src/main/java/team/startup/expo/domain/expo/Expo.java
src/main/java/team/startup/expo/domain/expo/presentation/ExpoController.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/request/GenerateExpoRequestDto.java
src/main/java/team/startup/expo/domain/expo/repository/ExpoRepository.java
src/main/java/team/startup/expo/domain/expo/service/GenerateExpoService.java
src/main/java/team/startup/expo/domain/expo/service/impl/GenerateExpoServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 생성 api를 추가하였습니다
Resolves: #31 
* generateExpo api 추가

🔀 :: 박람회 생성

---

src/main/java/team/startup/expo/domain/training/exception/NotFoundTrainingProgramException.java
src/main/java/team/startup/expo/domain/training/presentation/TrainingController.java
src/main/java/team/startup/expo/domain/training/presentation/dto/response/GetTrainingProTraineeResponseDto.java
src/main/java/team/startup/expo/domain/training/repository/TrainingProgramRepository.java
src/main/java/team/startup/expo/domain/training/repository/TrainingProgramUserRepository.java
src/main/java/team/startup/expo/domain/training/service/GetTraineeByTrainingProService.java
src/main/java/team/startup/expo/domain/training/service/impl/GetTraineeByTrainingProServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수 프로그램별로 연수자의 출석 상태를 반환하는 api를 추가하였습니다
Resolves: #33 
* GetTraineeByTrainingProgram api 추가
이 api는 N + 1 문제가 일어날 가능성이 높아 성능 최적화가 필요해보입니다.

🔀 :: 연수 프로그램별 연수자 출석부

---

build.gradle.kts

mariaDB의 의존성을 추가하였습니다.
Resolves: #35 
* 마리아디비 의존성 추가

🔀 :: mariaDB 의존성 추가

---

src/main/java/team/startup/expo/domain/expo/exception/NotFoundExpoException.java
src/main/java/team/startup/expo/domain/expo/exception/NotMatchAdminException.java
src/main/java/team/startup/expo/domain/expo/presentation/ExpoController.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/request/UpdateExpoRequestDto.java
src/main/java/team/startup/expo/domain/expo/service/UpdateExpoService.java
src/main/java/team/startup/expo/domain/expo/service/impl/UpdateExpoServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

등록한 박람회의 정보를 수정할 수 있는 api를 추가하였습니다.
Resolves: #37 
* UpdateExpo api 추가

🔀 :: 등록한 박람회 정보 수정

---

build.gradle.kts
src/main/java/team/startup/expo/domain/image/presentation/ImageController.java
src/main/java/team/startup/expo/domain/image/presentation/dto/response/UploadImageResponseDto.java
src/main/java/team/startup/expo/domain/image/service/UploadImageService.java
src/main/java/team/startup/expo/domain/image/service/impl/UploadImageServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java
src/main/java/team/startup/expo/global/thirdparty/aws/S3Config.java
src/main/java/team/startup/expo/global/thirdparty/aws/S3Util.java
src/main/java/team/startup/expo/global/thirdparty/aws/exception/FileExtensionInvalidException.java
src/main/resources/application.yml

aws S3를 이용한 image 업로드 api를 추가하였습니다
Resolves: #41 
* uploadImage api 추가
* S3Config 추가
* S3Util 추가

🔀 :: 이미지 업로드 api

---

build.gradle.kts
src/main/java/team/startup/expo/domain/expo/Expo.java
src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/participant/repository/ParticipantRepository.java
src/main/java/team/startup/expo/domain/sms/exception/NotFoundParticipantException.java
src/main/java/team/startup/expo/domain/sms/exception/NotFoundTraineeException.java
src/main/java/team/startup/expo/domain/sms/presentation/SmsController.java
src/main/java/team/startup/expo/domain/sms/presentation/dto/request/SendQrRequestDto.java
src/main/java/team/startup/expo/domain/sms/service/SendQrService.java
src/main/java/team/startup/expo/domain/sms/service/impl/SendQrServiceImpl.java
src/main/java/team/startup/expo/domain/standard/StandardProgram.java
src/main/java/team/startup/expo/domain/standard/StandardProgramUser.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java
src/main/java/team/startup/expo/domain/training/TrainingProgram.java
src/main/java/team/startup/expo/domain/training/TrainingProgramUser.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수자 혹은 관람객이 사전 신청 폼 작성을 끝낸 후 폼에 입력한 전화번호로 QR을 전송하는 api를 추가하였습니다
Resolves: #43 
* SendQR api 추가
* 모든 엔티티 연관관계 지연로딩 설정
처음 하는 QR 전송이라 코드가 지저분해보일 수 있습니다. 
최대한 비슷한 기능을 메서드로 묶어서 구조화 시켜 정리하였습니다.
또한, 코드 중복도를 낮추기 위해 중복되는 코드도 메서드화 시켜주었습니다.

🔀 :: QR 발송 api

---

src/main/java/team/startup/expo/domain/expo/Expo.java
src/main/java/team/startup/expo/domain/expo/presentation/ExpoController.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/response/GetExpoResponseDto.java
src/main/java/team/startup/expo/domain/expo/service/GetExpoService.java
src/main/java/team/startup/expo/domain/expo/service/impl/GetExpoServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 정보를 가져오는 api를 추가하였습니다
Resolves: #47 
* GetExpo api 추가
* Expo 엔티티에 x, y 추가

🔀 :: 박람회 정보 가져오기

---

src/main/java/team/startup/expo/domain/expo/presentation/dto/request/GenerateExpoRequestDto.java
src/main/java/team/startup/expo/domain/expo/service/impl/GenerateExpoServiceImpl.java

박람회 생성 중 x,y 좌표를 추가하지 않아 추가하는 로직을 추가하였습니다
Resolves: #49 
* GenerateExpo api 위치 x,y 추가

🔀 :: 박람회 생성 api 수정

---

src/main/java/team/startup/expo/global/security/config/WebMvcConfig.java

웹에서 접근한테 cors 문제가 생겨 WebMvcConfig를 추가하여 해당 오리진을 추가하였습니다
Resolves: #51 
* WebMvcConfig 추가

🔀 :: cors 설정

---

src/main/java/team/startup/expo/domain/training/presentation/TrainingController.java
src/main/java/team/startup/expo/domain/training/presentation/dto/request/AddTrainingProRequestDto.java
src/main/java/team/startup/expo/domain/training/service/AddTrainingProService.java
src/main/java/team/startup/expo/domain/training/service/impl/AddTrainingProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수 프로그램을 추가할 수 있는 api를 추가하였습니다
Resolves: #53 
* AddTrainingProgram api 추가

🔀 :: 연수 프로그램 추가

---

src/main/java/team/startup/expo/domain/training/presentation/TrainingController.java
src/main/java/team/startup/expo/domain/training/presentation/dto/request/UpdateTrainingProRequestDto.java
src/main/java/team/startup/expo/domain/training/service/UpdateTrainingProService.java
src/main/java/team/startup/expo/domain/training/service/impl/UpdateTrainingProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

관리자가 연수 프로그램을 수정할 수 있도록 api를 추가하였습니다.
Resolves: #55 
* UpdateTrainingPro api 추가

🔀 :: 연수 프로그램 수정

---

src/main/java/team/startup/expo/domain/expo/presentation/ExpoController.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/response/GetExpoInfoResponseDto.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/response/GetExpoResponseDto.java
src/main/java/team/startup/expo/domain/expo/service/GetExpoInfoService.java
src/main/java/team/startup/expo/domain/expo/service/GetExpoListService.java
src/main/java/team/startup/expo/domain/expo/service/GetExpoService.java
src/main/java/team/startup/expo/domain/expo/service/impl/GetExpoInfoInfoServiceImpl.java
src/main/java/team/startup/expo/domain/expo/service/impl/GetExpoListServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

모든 박람회를 불러오기 위한 api를 추가하였습니다
Resolves: #57 
* GetExpoList api 

🔀 :: 모든 박람회 불러오기

---

src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/standard/StandardProgramUser.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java
src/main/java/team/startup/expo/domain/training/TrainingProgram.java
src/main/java/team/startup/expo/domain/training/TrainingProgramUser.java
src/main/java/team/startup/expo/domain/training/presentation/TrainingController.java
src/main/java/team/startup/expo/domain/training/repository/TrainingProgramUserRepository.java
src/main/java/team/startup/expo/domain/training/service/DeleteTrainingProService.java
src/main/java/team/startup/expo/domain/training/service/impl/DeleteTrainingProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수 프로그램을 삭제할 수 있는 api를 추가하였습니다.
Resolves: #59 
* DeleteTrainingProgram api 삭제
모든 엔티티의 ManyToOne의 옵션을 수정하였습니다.

🔀 :: 연수 프로그램 삭제

---

src/main/java/team/startup/expo/domain/expo/presentation/dto/response/GetExpoResponseDto.java
src/main/java/team/startup/expo/domain/expo/service/impl/GetExpoListServiceImpl.java

박람회 리스트 response에 id가 포함되어 있지 않아 추가하였습니다
Resolves: #63 
* response에 id 추가

🔀 :: 박람회 리스트 api 수정

---

src/main/java/team/startup/expo/domain/attendance/exception/AlreadyLeaveProgramUserException.java
src/main/java/team/startup/expo/domain/attendance/exception/NotFoundTrainingProgramUserException.java
src/main/java/team/startup/expo/domain/attendance/presentation/AttendanceController.java
src/main/java/team/startup/expo/domain/attendance/presentation/dto/ScanTrainingProRequestDto.java
src/main/java/team/startup/expo/domain/attendance/service/ScanTrainingProByQrCodeService.java
src/main/java/team/startup/expo/domain/attendance/service/impl/ScanTrainingProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java
src/main/java/team/startup/expo/domain/training/TrainingProgramUser.java
src/main/java/team/startup/expo/domain/training/repository/TrainingProgramUserRepository.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수 프로그램 qr 인식을 하여 출석을 관리하기 위한 api를 추가하였습니다
* ScanTrainingProByQrCode api 추가

🔀 :: 연수 프로그램 qr 인식

---

src/main/java/team/startup/expo/domain/attendance/exception/NotFoundStandardProgramException.java
src/main/java/team/startup/expo/domain/attendance/exception/NotFoundStandardProgramUserException.java
src/main/java/team/startup/expo/domain/attendance/presentation/AttendanceController.java
src/main/java/team/startup/expo/domain/attendance/presentation/dto/request/ScanStandardProRequestDto.java
src/main/java/team/startup/expo/domain/attendance/presentation/dto/request/ScanTrainingProRequestDto.java
src/main/java/team/startup/expo/domain/attendance/service/ScanStandardProByQrCodeService.java
src/main/java/team/startup/expo/domain/attendance/service/ScanTrainingProByQrCodeService.java
src/main/java/team/startup/expo/domain/attendance/service/impl/ScanStandardProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/attendance/service/impl/ScanTrainingProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/standard/StandardProgramUser.java
src/main/java/team/startup/expo/domain/standard/repository/StandardProgramUserRepository.java
src/main/java/team/startup/expo/domain/training/repository/TrainingProgramUserRepository.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반 프로그램의 출석을 관리하기 위해 qr의 정보를 보내는 api를 추가하였습니다.
Resolves: #67 
* ScanStandardProByQrCode api 추가
#66 에서 구현하였던 조건문이 잘못되어 수정하였습니다

🔀 :: 일반 프로그램 QR 인식

---

src/main/java/team/startup/expo/domain/expo/presentation/dto/request/UpdateExpoRequestDto.java

박람회 수정 api에서 x, y 좌표를 받는 로직이 생략되어 추가하였습니다
Resolves: #69 
* 박람회 수정 api 요청에 x, y 추가

🔀 :: 박람회 수정 api x, y 추가

---

src/main/java/team/startup/expo/ExpoApplication.java

배포 후 서버의 시간이 현재 시간과 일치하지 않아 TimeZone을 설정하였습니다
Resolves: #71 
* PostConstruct를 사용하여 Application 클래스에 메서드를 추가하여 설정하였습니다

🔀 :: Server TimeZone 설정

---

src/main/java/team/startup/expo/domain/standard/presentation/StandardController.java
src/main/java/team/startup/expo/domain/standard/presentation/dto/request/AddStandardProRequestDto.java
src/main/java/team/startup/expo/domain/standard/service/AddStandardProService.java
src/main/java/team/startup/expo/domain/standard/service/impl/AddStandardProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반 프로그램을 추가하는 api를 추가하였습니다
Resolves: #73 
* AddStandardProgram api 추가

🔀 :: 일반 프로그램 추가

---

build.gradle.kts
src/main/java/team/startup/expo/global/filter/ExceptionFilter.java
src/main/java/team/startup/expo/global/filter/RequestLogFilter.java
src/main/java/team/startup/expo/global/filter/event/ErrorLoggingEvent.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java
src/main/java/team/startup/expo/global/thirdparty/discord/ErrorEventHandler.java
src/main/java/team/startup/expo/global/thirdparty/discord/properties/DiscordProperties.java
src/main/resources/application.yml

서버 에러를 매번 확인하는 것보다 디스코드로 볼 수 있게 하기 위해 웹훅을 연결하였습니다.
이벤트 핸들러를 추가하여 만약에 오류가 난다면 필터에서 이벤트를 호출해 디스코드로 알림을 보내는 로직을 실행시켜 알림을 보내게 하였습니다
- [] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `.env`, `노션`, `README`)

🔀 :: 서버 에러 디스코드 웹훅 연동

---

src/main/java/team/startup/expo/domain/training/presentation/TrainingController.java
src/main/java/team/startup/expo/domain/training/presentation/dto/request/AddTrainingProRequestDto.java
src/main/java/team/startup/expo/domain/training/service/AddTrainingProListService.java
src/main/java/team/startup/expo/domain/training/service/impl/AddTrainingProListServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수 프로그램을 리스트로 요청을 받아 추가하는 코드를 추가하였습니다
Resolves: #79 
* AddTrainingProgramList api 추가
* AddTrainingProRequestDto 필드에 NotNull 추가

🔀 :: 연수 프로그램 리스트 추가

---

src/main/java/team/startup/expo/domain/standard/presentation/StandardController.java
src/main/java/team/startup/expo/domain/standard/presentation/dto/request/AddStandardProRequestDto.java
src/main/java/team/startup/expo/domain/standard/service/AddStandardProListService.java
src/main/java/team/startup/expo/domain/standard/service/impl/AddStandardProListServiceImpl.java
src/main/java/team/startup/expo/domain/standard/service/impl/AddStandardProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반 프로그램을 여러개 동시에 추가할 수 있는 api를 추가하였습니다
Resolves: #81 
* AddStandardProgramList api 추가
* AddStandardProRequestDto 변경
전에 Dto에서 날짜 형식을 맞추지 않아도 통과되었던 문제가 있어 해결하였습니다.
하지만 연수 프로그램 추가 Dto는 아직 해결하지 않아 해결하여야합니다.

🔀 :: 일반 프로그램 여러개 추가

---

src/main/java/team/startup/expo/domain/attendance/presentation/AttendanceController.java
src/main/java/team/startup/expo/domain/expo/presentation/ExpoController.java
src/main/java/team/startup/expo/domain/standard/presentation/StandardController.java
src/main/java/team/startup/expo/domain/standard/presentation/dto/request/UpdateStandardProRequestDto.java
src/main/java/team/startup/expo/domain/standard/service/UpdateStandardProService.java
src/main/java/team/startup/expo/domain/standard/service/impl/UpdateStandardProServiceImpl.java
src/main/java/team/startup/expo/domain/training/presentation/TrainingController.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반 프로그램을 수정하는 api를 추가하였습니다
Resolves: #85 
* 일반 프로그램 수정 api 추가
* 컨트롤러 Valid 추가
Dto에 유효성 검사를 추가하였는데 Valid 어노테이션을 추가하지 않아서 유효성 검사가 되지 않는 것을 깨닫고 추가하였습니다~

🔀 :: 일반 프로그램 수정

---

src/main/java/team/startup/expo/domain/standard/StandardProgram.java
src/main/java/team/startup/expo/domain/standard/presentation/StandardController.java
src/main/java/team/startup/expo/domain/standard/repository/StandardProgramUserRepository.java
src/main/java/team/startup/expo/domain/standard/service/DeleteStandardProService.java
src/main/java/team/startup/expo/domain/standard/service/impl/DeleteStandardProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

등록된 일반 프로그램을 삭제할 수 있는 api를 추가하였습니다
Resolves: #89 
* DeleteStandardProgram api 추가
* Expo ManyToOne cascade 옵션 삭제

🔀 :: 일반 프로그램 삭제

---

src/main/java/team/startup/expo/domain/standard/presentation/StandardController.java
src/main/java/team/startup/expo/domain/standard/presentation/dto/response/GetStandardProgramResponseDto.java
src/main/java/team/startup/expo/domain/standard/repository/StandardProgramRepository.java
src/main/java/team/startup/expo/domain/standard/service/GetStandardProListService.java
src/main/java/team/startup/expo/domain/standard/service/impl/GetStandardProListServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

해당 박람회의 일반 프로그램의 리스트를 불러오는 api를 추가하였습니다
Resolves: #91 
* GetStandardProgramList api 추가

🔀 :: 일반 프로그램 리스트 api

---

src/main/java/team/startup/expo/domain/standard/presentation/StandardController.java
src/main/java/team/startup/expo/domain/standard/presentation/dto/response/GetStandardProParticipantResponseDto.java
src/main/java/team/startup/expo/domain/standard/repository/StandardProgramUserRepository.java
src/main/java/team/startup/expo/domain/standard/service/GetParticipantByStandardProService.java
src/main/java/team/startup/expo/domain/standard/service/impl/GetParticipantByStandardProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반 프로그램별 출석 현황을 조회할 수 있는 api를 추가하였습니다
Resolves: #92 
* GetParticipantByStandardPro api 추가
N + 1 문제가 발생하는 것이 확인되어 모든 기능을 개발한 후 리팩토링 진행하겠습니다

🔀 :: 일반 프로그램별 출석 현황 조회

---

src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/presentation/dto/request/PreApplicationForTraineeRequestDto.java
src/main/java/team/startup/expo/domain/form/service/PreApplicationForTraineeService.java
src/main/java/team/startup/expo/domain/form/service/impl/PreApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수자 사전 신청하는 api를 추가하였습니다
Resolves: #95 
* PreApplicationForTrainee api 추가
원래 폼이 동적으로 해야되지만 임시로 정적으로 하였습니다. 
나중에 변경될 것 같습니다

🔀 :: 연수자 사전 신청 

---

src/main/java/team/startup/expo/domain/sms/service/impl/SendQrServiceImpl.java

QR 안에 있는 값을 변경하였습니다
Resolves: #103 
* QR 안 내용 변경

🔀 :: QR 값 변경

---

src/main/java/team/startup/expo/domain/training/presentation/TrainingController.java
src/main/java/team/startup/expo/domain/training/presentation/dto/request/ApplicationTrainingProRequestDto.java
src/main/java/team/startup/expo/domain/training/repository/TrainingProgramUserRepository.java
src/main/java/team/startup/expo/domain/training/service/ApplicationTrainingProService.java
src/main/java/team/startup/expo/domain/training/service/impl/ApplicationTrainingProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수 사전 신청을 진행하며 연수 프로그램을 신청할 수 있는 api를 추가하였습니다.
Resolves: #113 
* ApplicationTrainingPro api 추가

🔀 :: 연수 프로그램 신청

---

src/main/java/team/startup/expo/domain/trainee/Trainee.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java
src/main/java/team/startup/expo/domain/training/presentation/TrainingController.java
src/main/java/team/startup/expo/domain/training/presentation/dto/request/ApplicationTrainingProListRequestDto.java
src/main/java/team/startup/expo/domain/training/presentation/dto/request/ApplicationTrainingProRequestDto.java
src/main/java/team/startup/expo/domain/training/service/ApplicationTrainingProListService.java
src/main/java/team/startup/expo/domain/training/service/impl/ApplicationTrainingProListServiceImpl.java
src/main/java/team/startup/expo/domain/training/service/impl/ApplicationTrainingProServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

연수 프로그램을 동시에 여러개 신청할 수 있는 api를 추가하였습니다
Resolves: #115 
* ApplicationTrainingProList api 추가
연수원 아이디는 중복이 되면 안되는 컬럼이기 때문에 unique 속성을 추가하였습니다.
또한, #114 에서 Trainee 의 id와 착각하여 로직을 잘못 짜여져 올바르게 수정하였습니다

🔀 :: 연수 프로그램 동시에 여러개 신청

---

src/main/java/team/startup/expo/domain/expo/exception/NotExistParticipantAtExpoException.java
src/main/java/team/startup/expo/domain/expo/exception/NotExistTraineeAtExpoException.java
src/main/java/team/startup/expo/domain/participant/repository/ParticipantRepository.java
src/main/java/team/startup/expo/domain/sms/presentation/SmsController.java
src/main/java/team/startup/expo/domain/sms/presentation/dto/request/SendMessageRequestDto.java
src/main/java/team/startup/expo/domain/sms/service/SendMessageService.java
src/main/java/team/startup/expo/domain/sms/service/impl/SendMessageServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반 관람객과 교원연수자를 선택하여 단체 문자를 전송하는 api를 추가하였습니다
Resolves: #123 
* sendMessage api 추가

🔀 :: 교원연수자 및 일반 관람객 단체 문자 전송

---

src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java

박람회를 다중으로 신청하기 위해 컬럼 조건을 변경할 수 있도록 수정하겠습니다
Resolves: #125 
* ExpoParticipant와 Trainee 컬럼 중 unique가 들어간 컬럼의 조건을 삭제

🔀 :: 박람회 다중 신청을 위한 컬럼 조건 변경

---

src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/presentation/dto/request/ApplicationForTraineeRequestDto.java
src/main/java/team/startup/expo/domain/form/service/FieldApplicationForTraineeService.java
src/main/java/team/startup/expo/domain/form/service/PreApplicationForTraineeService.java
src/main/java/team/startup/expo/domain/form/service/impl/FieldApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/PreApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

교원연수를 현장에서 신청할 수 있는 api를 추가하였습니다
Resolves: #129 
* FieldApplicationForTrainee api 추가
* PreApplicationForTraineeRequestDto -> ApplicationForTraineeRequestDto 변경

🔀 :: 교원연수 현장 신청

---

src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/presentation/dto/request/ApplicationForParticipantRequestDto.java
src/main/java/team/startup/expo/domain/form/service/FieldApplicationForParticipantService.java
src/main/java/team/startup/expo/domain/form/service/PreApplicationForParticipantService.java
src/main/java/team/startup/expo/domain/form/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반관람객이 현장에서 현장신청을 할 수 있는 api를 추가하였습니다
Resolves: #131 
* fieldApplicationForParticipant api 추가

🔀 :: 일반관람객 현장 신청

---

src/main/java/team/startup/expo/domain/attendance/service/impl/ScanStandardProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/attendance/service/impl/ScanTrainingProByQrCodeServiceImpl.java

연수와 일반 프로그램의 입실과 퇴실이 잘못 입력되는 오류가 생겨 로직을 수정하였습니다
Resolves: #138 
* ScanStandardProByQrCode api 수정
* ScanTrainingProByQrCode api 수정

🔀 :: 연수 프로그램 및 일반 프로그램 입실, 퇴실 시간 입력 오류

---

src/main/java/team/startup/expo/domain/form/entity/Form.java
src/main/java/team/startup/expo/domain/form/exception/NotFoundFormException.java
src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/presentation/dto/request/FormRequestDto.java
src/main/java/team/startup/expo/domain/form/repository/DynamicFormRepository.java
src/main/java/team/startup/expo/domain/form/service/CreateFormService.java
src/main/java/team/startup/expo/domain/form/service/UpdateFormService.java
src/main/java/team/startup/expo/domain/form/service/impl/CreateFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/UpdateFormServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

폼 수정하기 api를 추가하였습니다
Resolves: #144 
* UpdateForm api 추가
api를 제작 후 테스트 시에 올바르게 DynamicForm에 해당하는 값들이 수정이 잘 되지 않는 문제점이 발견되어 수정하는 동시에 해당 Form에 DynamicForm 값들을 모두 지우고 다시 생성하는 방식으로 수정하였습니다

🔀 :: 폼 수정 api

---

src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/service/DeleteFormService.java
src/main/java/team/startup/expo/domain/form/service/impl/DeleteFormServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

폼을 삭제하는 동시에 동적 폼까지 삭제할 수 있도록 api를 개발하였습니다
Resolves: #146 
* DeleteForm api 추가

🔀 :: 폼 삭제 api

---

src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/presentation/dto/GetFormResponseDto.java
src/main/java/team/startup/expo/domain/form/repository/DynamicFormRepository.java
src/main/java/team/startup/expo/domain/form/service/GetFormService.java
src/main/java/team/startup/expo/domain/form/service/impl/GetFormServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

생성된 폼을 가져오는 api를 추가하였습니다
Resolves: #148 
* GetForm api 추가

🔀 :: 생성된 폼 가져오기

---

src/main/java/team/startup/expo/domain/participant/presentation/dto/response/GetParticipantInfoResponseDto.java
src/main/java/team/startup/expo/domain/standard/presentation/dto/response/GetStandardProParticipantResponseDto.java
src/main/java/team/startup/expo/domain/trainee/presentation/dto/response/GetTraineeInformationResponseDto.java
src/main/java/team/startup/expo/domain/training/presentation/dto/response/GetTrainingProTraineeResponseDto.java

동적폼으로 변경하는 동시에 사용하지 않는 Response들을 코드에서 삭제하였습니다
Resolves: #150 
* GetParticipantInfoResponseDto 필드 수정
* GetStandardProParticipantResponseDto 필드 수정
* GetTraineeInformationResponseDto 필드 수정
* GetTrainingProTraineeResponseDto 필드 수정
1. 연수 프로그램별 교원연수 출석부 API 수정
2. 일반 프로그램별 출석 리스트 API 수정
3. 박람회 사전 및 현장 신청 관람객 정보 API 수정
4. 모든 교원연수 정보 API 수정

🔀 :: 동적폼에 의해 변경된 Response 적용

---

src/main/java/team/startup/expo/domain/admin/exception/AlreadyAcceptUserException.java
src/main/java/team/startup/expo/domain/admin/presentation/AdminController.java
src/main/java/team/startup/expo/domain/admin/service/RefuseAdminService.java
src/main/java/team/startup/expo/domain/admin/service/impl/RefuseAdminServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

관리자 요청을 거절하는 api를 추가하였습니다
Resolves: #152 
* RefuseAdmin api 추가

🔀 :: 관리자 요청 거절

---

src/main/java/team/startup/expo/domain/admin/entity/Admin.java
src/main/java/team/startup/expo/domain/expo/entity/Expo.java
src/main/java/team/startup/expo/domain/form/entity/DynamicForm.java
src/main/java/team/startup/expo/domain/form/entity/Form.java
src/main/java/team/startup/expo/domain/participant/entity/StandardParticipant.java
src/main/java/team/startup/expo/domain/participant/entity/StandardParticipantParticipation.java
src/main/java/team/startup/expo/domain/standard/entity/StandardProgram.java
src/main/java/team/startup/expo/domain/standard/entity/StandardProgramUser.java
src/main/java/team/startup/expo/domain/trainee/entity/Trainee.java
src/main/java/team/startup/expo/domain/trainee/entity/TraineeParticipation.java
src/main/java/team/startup/expo/domain/training/entity/TrainingProgram.java
src/main/java/team/startup/expo/domain/training/entity/TrainingProgramUser.java

데이터베이스에 테이블이 생성되지 않는 문제를 해결하였습니다
Resolves: #155 
데이터베이스에 테이블이 생성되지 않는 문제를 `@Table`를 사용하여 테이블이 생성될 때 이름을 지정해주었습니다.
확실하진 않지만 데이터베이스에서 명령어로 사용되는 엔티티의 이름이 있는 것 같아 지정하여 그러한 문제가 생기지 않도록 예방하였습니다
mysql에서는 문제가 생기지 않지만 mariadb에서 문제가 생겨 수정하였습니다

🔀 :: 데이터베이스에 테이블이 생성되지 않는 문제

---

src/main/java/team/startup/expo/domain/standard/presentation/StandardController.java
src/main/java/team/startup/expo/domain/standard/presentation/dto/request/ApplicationStandardProListRequestDto.java
src/main/java/team/startup/expo/domain/standard/repository/StandardProgramUserRepository.java
src/main/java/team/startup/expo/domain/standard/service/ApplicationStandardProListService.java
src/main/java/team/startup/expo/domain/standard/service/impl/ApplicationStandardProListServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반 프로그램을 여러개 신청할 수 있는 api를 추가하였습니다
Resolves: #154 
* ApplicationStandardProList api 추가
>
>

🔀 :: 일반 프로그램 여러개 신청

---

src/main/java/team/startup/expo/domain/trainee/service/impl/GetTrainingInformationServiceImpl.java

Dto에는 있지만 빌더로 초기화해주지 않아 반환되지 않는 것을 수정하였습니다
Resolves: #158 
* 모든 교원연수 정보 api 반환값 trainingId 추가

🔀 :: 모든 교원연수 정보 api 반환값 수정

---

src/main/java/team/startup/expo/domain/participant/presentation/ParticipantController.java
src/main/java/team/startup/expo/domain/participant/repository/ParticipantRepository.java
src/main/java/team/startup/expo/domain/participant/service/GetParticipantInfoService.java
src/main/java/team/startup/expo/domain/participant/service/impl/GetParticipantInfoServiceImpl.java
src/main/java/team/startup/expo/domain/trainee/presentation/TraineeController.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java
src/main/java/team/startup/expo/domain/trainee/service/GetTrainingInformationService.java
src/main/java/team/startup/expo/domain/trainee/service/impl/GetTrainingInformationServiceImpl.java

일반 참가자와 교원연수자를 검색할 수 있도록 조회 api에 이름을 파라미터로 추가하여 추가로 검색을 할 수 있도록 수정하였습니다
Resolves: #160 
* GetTraineeInformation api 수정
* GetParticipantInfo api 수정

🔀 :: 일반 참가자와 교원연수자 검색 api

---

src/main/java/team/startup/expo/domain/application/presentation/dto/request/ApplicationForParticipantRequestDto.java
src/main/java/team/startup/expo/domain/application/presentation/dto/request/ApplicationForTraineeRequestDto.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForTraineeServiceImpl.java

동적폼을 박람회 신청에 맞게 수정하지 않아 오류가 일어나 수정하였습니다
Resolves: #162 
* all Application api 수정
>
>

🔀 :: 동적폼에 맞게 신청 api 수정

---

build.gradle.kts
src/main/java/team/startup/expo/global/exception/GlobalExceptionHandler.java

GlobalExceptionHandler에 에러를 핸들러 해놓지 않아 통신을 하며 원활하게 되지 않아 에러들을 핸들링하였습니다
Resolves: #168 
* GlobalExceptionHandler에서 여러 에러 핸들링 처리

🔀 :: ExceptionHandler 문제

---

src/main/java/team/startup/expo/domain/expo/entity/Expo.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/request/GenerateExpoRequestDto.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/request/UpdateExpoRequestDto.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/response/GetExpoInfoResponseDto.java

박람회 생성 중 위도 경도가 소수점 3자리에서 반올림되는 문제가 생겨 변경하겠습니다
Resolves: #170
* 위도 경도 Float -> String 변경

🔀 :: 박람회 생성 중 위도 경도 문제

---

.github/workflows/Expo-CD.yml
appspec.yml
build.gradle.kts
settings.gradle.kts
start.sh
stop.sh

GithubAction을 이용하여 ec2에 자동으로 cd를 할 수 있도록 스크립트를 추가하였습니다
Resolves: #174 
GithubAction을 사용하여 Expo-CD.yml을 추가하여 AWS의 CodeDeploy를 사용하여 cd를 진행하였습니다
cd를 처음 해보는 거라 잘 적용되는지 테스트 진행하겠습니다

🔀 :: cd 구축

---

start.sh

start.sh에서 JAR_FILE 변수를 인식하지 못하고 문자열로 인식하는 오류가 생겨 변수라고 지정해주었습니다
Resolves: #177 
* start.sh 수정
>
>

🔀 :: cd 스크립트 수정

---

appspec.yml
start.sh

JAR_FILE의 권한을 111로 주어서 실행하는데 permission denied가 뜨는 문제가 생겨 777로 변경하였습니다
Resolves: #179 
* start.sh에서 JAR_FILE의 권한을 111에서 777로 변경하였습니다

🔀 :: cd 권한문제

---

src/main/java/team/startup/expo/domain/admin/presentation/AdminController.java
src/main/java/team/startup/expo/domain/admin/presentation/dto/response/GetMyInformationResponseDto.java
src/main/java/team/startup/expo/domain/admin/service/GetMyInformationService.java
src/main/java/team/startup/expo/domain/admin/service/impl/GetMyInformationServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

관리자가 로그인 후 자신의 정보를 불러올 수 있는 api를 추가하였습니다
Resolves: #187 
* GetMyInformation api 추가

🔀 :: 관리자 자신의 정보 가져오기

---

src/main/java/team/startup/expo/domain/form/entity/DynamicForm.java
src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/presentation/dto/request/FormRequestDto.java
src/main/java/team/startup/expo/domain/form/presentation/dto/response/GetFormResponseDto.java
src/main/java/team/startup/expo/domain/form/service/GetFormService.java
src/main/java/team/startup/expo/domain/form/service/impl/CreateFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/GetFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/UpdateFormServiceImpl.java

동적폼 기타사항 및 필수여부가 필요하여 추가하였습니다
Resolves: #191 
* 기타사항(otherJson)을 추가하여 비어있으면 Null로 없는 것이고 Not Null로 존재한다면 기타사항이 존재
* 필수사항 여부(requiredStatus)를 추가하여 이 질문이 필수사항인지 아닌지를 추가

🔀 :: 동적폼 기타사항 및 필수여부 추가

---

src/main/java/team/startup/expo/domain/form/entity/DynamicForm.java
src/main/java/team/startup/expo/domain/survey/entity/DynamicSurvey.java
src/main/java/team/startup/expo/domain/survey/entity/Survey.java

설문조사 관련해서 Survey와 DynamicSurvey 엔티티 세팅을 하였습니다.
Resolves: #193 
* Survey 엔티티 세팅
* DynamicSurvey 엔티티 세팅

🔀 :: 설문조사 관련 도메인 세팅

---

src/main/java/team/startup/expo/domain/survey/exception/NotFoundSurveyException.java
src/main/java/team/startup/expo/domain/survey/presentation/SurveyController.java
src/main/java/team/startup/expo/domain/survey/presentation/dto/response/SurveyResponseDto.java
src/main/java/team/startup/expo/domain/survey/repository/DynamicSurveyRepository.java
src/main/java/team/startup/expo/domain/survey/repository/SurveyRepository.java
src/main/java/team/startup/expo/domain/survey/service/GetSurveyService.java
src/main/java/team/startup/expo/domain/survey/service/impl/GetSurveyServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 설문조사 폼을 불러오는 api를 추가하였습니다
Resolves: #197 
* GetSurvey api 추가

🔀 :: 박람회 설문조사 불러오기

---

src/main/java/team/startup/expo/domain/participant/entity/StandardParticipantParticipation.java
src/main/java/team/startup/expo/domain/trainee/entity/TraineeParticipation.java

일반과 연수자의 참가 엔티티의 leaveTime에 Column을 수정하였습니다.
Resolves: #209 
* leaveTime을 Column 수정

🔀 :: Participation 컬럼 변경

---

src/main/java/team/startup/expo/global/security/config/WebMvcConfig.java

클라이언트 배포된 도메인을 허용하기 위해 추가하였습니다
Resolves: #215 
* 배포된 클라이언트 서버 도메인 허용

🔀 :: 클라이언트 도메인 CORS 허용

---

src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

로그 필터의 순서가 섞여 제대로 서버 로그가 찍히지 않는 문제가 생겨 수정하였습니다
* SecurityConfig에서 UsernamePasswordAuthenticationFilter 필터 전 로그 필터 순서 설정

🔀 :: 로그 필터 순서 변경

---

src/main/java/team/startup/expo/domain/excel/presentation/ExcelController.java
src/main/java/team/startup/expo/domain/excel/service/StandardParticipantInfoToExcelService.java
src/main/java/team/startup/expo/domain/excel/service/impl/StandardParticipantInfoToExcelServiceImpl.java
src/main/java/team/startup/expo/domain/participant/entity/StandardParticipant.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

모든 정보를 Excel로 출력할 수 있는 api를 추가하였습니다
Resolves: #221 
* 일반 참가자의 모든 정보와 Enum을 한글로 핸들링한 결과를 Excel로 반환하는 api 개발

🔀 :: 일반 참가자 정보 엑셀 출력

---

build.gradle.kts
docker-compose.yml
prometheus.yml
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java
src/main/resources/application.yml

실제 배포하여 사용할 때의 메트릭을 수집과 시각화하기 위해 prometheus와 grafana를 이용하여 서버 모니터링을 진행하였습니다
Resolves: #213 
* prometheus와 grafana를 도커에 띄우기 위한 설정
* actuator 엔드포인트 설정
EC2로 서버를 띄운 후에도 모니터링이 되는지 확인해야됩니다.

🔀 :: prometheus와 grafana를 이용한 서버 모니터링

---

.gitignore
prometheus.yml

테스트 서버에서 모니터링이 되지 않는 문제가 발생하여 설정을 변경해주었습니다
Resolves: #231 
* prometheus gitiignore 처리
* prometheus.yml 타켓 변경

🔀 :: 테스트서버의 모니터링 문제

---

src/main/java/team/startup/expo/domain/application/presentation/ApplicationController.java
src/main/java/team/startup/expo/domain/application/presentation/dto/request/ApplicationTemporaryQrRequestDto.java
src/main/java/team/startup/expo/domain/application/presentation/dto/response/ApplicationTemporaryQrResponseDto.java
src/main/java/team/startup/expo/domain/application/service/FieldApplicationTemporaryQrService.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationTemporaryQrServiceImpl.java
src/main/java/team/startup/expo/domain/participant/repository/StandardParticipantRepository.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

전화번호 없이 임시 QR을 생성할 수 있는 api를 개발하였습니다
Resolves: #237 
* FieldApplicationTemporaryQr Api 개발

🔀 :: 전화번호 없이 임시 QR 생성 API

---

src/main/java/team/startup/expo/domain/expo/presentation/ExpoController.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/response/GetExpoValidationStatusResponseDto.java
src/main/java/team/startup/expo/domain/expo/service/GetExpoValidationStatusService.java
src/main/java/team/startup/expo/domain/expo/service/impl/GetExpoValidationStatusServiceImpl.java
src/main/java/team/startup/expo/domain/form/entity/DynamicForm.java
src/main/java/team/startup/expo/domain/form/repository/DynamicFormRepository.java
src/main/java/team/startup/expo/domain/form/repository/FormRepository.java
src/main/java/team/startup/expo/domain/survey/management/repository/SurveyRepository.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 동적폼, 만족도 조사 생성 여부 API를 개발 하였습니다.
Resolves: #241
- GetExpoValidationStatus api 개발

박람회 동적폼, 만족도 조사 생성 여부

---

src/main/java/team/startup/expo/domain/attendance/service/impl/ScanStandardProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/standard/repository/StandardProgramUserRepository.java

프로그램 참가 시 중복 참여가 될 수 있기 때문에 row lock을 걸어 동시성을 제어하였습니다
Resolves: #258 
* StandardProgramUser를 select할 때 row lock을 걸어 동시성 제어를 하였습니다

🔀 :: 프로그램 참가 row lock 적용

---

src/main/java/team/startup/expo/domain/attendance/presentation/dto/response/PreEnterScanQrCodeResponseDto.java
src/main/java/team/startup/expo/domain/attendance/service/impl/PreEnterScanQrCodeServiceImpl.java

박람회 입장시 오는 response에 스펙이 변경되었습니다
Resolves: #262 
* id와 participationType 필드 추가

🔀 :: 박람회 입장 response 변경

---

src/main/java/team/startup/expo/domain/survey/management/presentation/dto/response/SurveyResponseDto.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/GetSurveyServiceImpl.java

설문조사 불러오기에 informationText가 반환되지 않아 추가하였습니다.
Resolves: 
responseDto에 informationText 필드 추가

🔀 :: 설문조사 불러오기 response 변경

---

src/main/java/team/startup/expo/domain/expo/presentation/ExpoController.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/response/GetExpoValidationStatusResponseDto.java
src/main/java/team/startup/expo/domain/expo/service/GetExpoValidationStatusService.java
src/main/java/team/startup/expo/domain/expo/service/impl/GetExpoValidationStatusServiceImpl.java
src/main/java/team/startup/expo/domain/form/repository/FormRepository.java

박람회 폼, 설문조사 생성 여부 api의 스펙이 변경되어 수정하였습니다
Resolves: #265 
* api 스펙 변경 및 로직 변경
현재 api에서 한번 호출 될때마다 expo N개 X 4의 쿼리가 발생하여 나중에 캐시로 성능 개선이 필요합니다.

🔀 :: 박람회 폼, 설문조사 생성 여부 API spec 수정

---

src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationTemporaryQrServiceImpl.java
src/main/java/team/startup/expo/domain/participant/presentation/ParticipantController.java
src/main/java/team/startup/expo/domain/participant/repository/custom/ParticipantCustomRepository.java
src/main/java/team/startup/expo/domain/participant/repository/custom/impl/ParticipantCustomRepositoryImpl.java
src/main/java/team/startup/expo/domain/participant/service/GetParticipantInfoService.java
src/main/java/team/startup/expo/domain/participant/service/impl/GetParticipantInfoServiceImpl.java

date가 박람회 시작과 끝나는 날짜 사이에 있는 사람들을 불러오고 where 조건문이 올바르지 않아 수정하였습니다.
Resolves: 
where 조건문이 잘못된 곳을 수정하였습니다.

🔀 :: 일반 참가자 불러와지지 않는 문제 해결

---

src/main/java/team/startup/expo/domain/survey/answer/entity/StandardParticipantSurveyAnswer.java
src/main/java/team/startup/expo/domain/survey/answer/entity/TraineeSurveyAnswer.java
src/main/java/team/startup/expo/domain/survey/answer/presentation/dto/request/SurveyAnswerRequestDto.java
src/main/java/team/startup/expo/domain/survey/answer/service/impl/StandardSurveyAnswerServiceImpl.java
src/main/java/team/startup/expo/domain/survey/answer/service/impl/TraineeSurveyAnswerServiceImpl.java

설문조사 시에 개인정보 동의할 수 있는 여부를 저장하기 위해 추가하였습니다.
연수자/일반 참가자 설문조사 답변 엔티티에 개인정도 동의 여부 컬럼 추가

🔀 :: 설문조사 참여 개인정보 동의 여부 컬럼 추가

---

src/main/java/team/startup/expo/domain/excel/service/impl/StandardParticipantInfoToExcelServiceImpl.java
src/main/java/team/startup/expo/domain/excel/service/impl/TraineeInfoToExcelServiceImpl.java

모든 유저의 정보가 똑같이 들어가는 문제를 해결하였습니다.
* List의 0번쨰 인덱스를 가져와 헤더를 구성하고 정보를 넣을 때는 초기화해야되는데 0번쨰 유저의 정보가 일괄적으로 들어가는 문제를 for문을 돌때마다 각 유저를 가져와 정보를 넣는 방식으로 변경하였습니다.
>
>

🔀 :: Excel 출력 오류

---

src/main/java/team/startup/expo/domain/application/presentation/dto/response/ApplicationTemporaryQrResponseDto.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationTemporaryQrServiceImpl.java

클라이언트가 로직을 처리하며 expoId가 필요하여 임시 QR에 expoId를 추가반환하였습니다.
* 임시 QR에 expoId 추가반환
>
>

🔀 :: 임시 QR 발급에 expoId 추가 반환

---

src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

임시 QR api를 관리자만 사용할 수 있도록 수정하였습니다.
* permitAll() -> hasAnyAuthority(Authority.ROLE_ADMIN.name())
>
>

🔀 :: 임시 QR 발급 접근 권한 설정

---

src/main/java/team/startup/expo/domain/excel/presentation/ExcelController.java
src/main/java/team/startup/expo/domain/excel/service/ProgramParticipantInfoToExcelService.java
src/main/java/team/startup/expo/domain/excel/service/impl/ProgramParticipantInfoToExcelServiceImpl.java
src/main/java/team/startup/expo/domain/standard/repository/StandardProgramRepository.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

프로그램을 참여한 참가자들의 정보를 엑셀로 출력할 수 있는 API를 개발하였습니다.
* ProgramParticipantInfoToExcel API 개발
정보를 출력한 후 학번과 비고를 만들어 학생들의 정보를 적을 수 있도록 하였습니다.

🔀 :: 프로그램 참가자 엑셀 출력

---

src/main/java/team/startup/expo/ExpoApplication.java
src/main/java/team/startup/expo/domain/application/event/handler/SendQrEventHandler.java
src/main/java/team/startup/expo/domain/attendance/event/handler/EnterSmsEventHandler.java
src/main/java/team/startup/expo/global/config/AsyncConfig.java

Async의 Executor 설정을 추가하였습니다.
Async를 아무 설정하고 사용하지 않으면 쓰레드를 무한정 생성하여 OOM이 발생할 수도 있어 쓰레드를 제한하는 AsyncConfig를 추가하였습니다.
>
>

🔀 :: Async Executor 설정 추가

---

src/main/java/team/startup/expo/domain/excel/service/impl/ProgramParticipantInfoToExcelServiceImpl.java

프로그램 참가자 엑셀 출력에서 헤더의 구성요소를 추가하였습니다.
* '서명' 헤더 추가
* Set으로 나머지 헤더를 추가할 때 순서가 보장되지 않아 List로 변경하여 순서를 보장하였습니다.
>
>

🔀 :: 프로그램 엑셀 출력 헤더 구성요소 변경

---

buildspec.yml

> PR을 하게 된 문제상황, 배경 및 개요에 대해서 작성해주세요!
>
> 퍼블리싱의 경우 스크린샷/동영상도 추가해주면 좋아요!
> PR에서 한 작업을 작성해주세요!
>
>

add buildspec

---

src/main/java/team/startup/expo/domain/application/event/handler/SendQrEventHandler.java
src/main/java/team/startup/expo/domain/image/service/impl/UploadImageServiceImpl.java
src/main/java/team/startup/expo/global/thirdparty/aws/S3Util.java
src/main/resources/application.yml

원래 QR 이미지를 반환하던 것을 링크로 반환하도록 하였습니다.
* ImageBucket, QRBucket 분리
>
>

🔀 :: 사전 등록/현장 등록 SMS QR 링크 발송

---

src/main/java/team/startup/expo/global/redis/RedisConfig.java
src/main/resources/application.yml

Redis에 SSL 설정하였습니다.
* yml에 Redis SSL enable true
>
>

🔀 :: Redis SSL 설정

---

src/main/java/team/startup/expo/domain/excel/service/impl/StandardParticipantInfoToExcelServiceImpl.java

엑셀 NPE가 발생하여 로직으로 핸들링 하였습니다.
참가자 엑셀 NPE 핸들링
>
>

🔀 :: 엑셀 NPE FIX

---

src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationTemporaryQrServiceImpl.java

임시 참가자 전화번호에 하이픈을 빼고 생성하도록 변경하였습니다.
* 임시 전화번호 "-" 제거
>
>

🔀 :: 임시 참가자 전화번호 생성 방법 변경

---

src/main/java/team/startup/expo/domain/application/event/handler/SendQrEventHandler.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationTemporaryQrServiceImpl.java
src/main/java/team/startup/expo/global/thirdparty/aws/S3Util.java

사전/현장 등록시 버킷 링크를 SMS로 보내는 것을 CF와 연결하여 QR을 보내도록 수정하였습니다.
* messageText 수정
>
>

🔀 :: 등록 SMS CF 링크 연결

---

src/main/java/team/startup/expo/global/thirdparty/aws/S3Util.java

이미지 업로드를 CF를 적용하여 url을 반환하도록 하였습니다.
* imageURL CF 적용
>
>

🔀 :: 이미지 업로드 url CF 적용

---

src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java

사전등록시 잘못된 applicationType이 초기화되어 수정하였습니다.
* 사전등록시 StandardParticipant 초기화시 `FIELD` -> `PRE` 변경
>
>

🔀 :: 사전등록시 잘못된 applicationType 수정

---

src/main/java/team/startup/expo/global/security/jwt/JwtProvider.java

실제 사용하기 전 엑세스 만료로 인해 지연될 가능성으로 엑세스 토큰의 시간을 일시적으로 늘렸습니다.
* 엑세스 토큰 15분 -> 1일
보안적 이슈가 생길 수 있습니다.

🔀  :: accessToken Expired time 변경

---

src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java

> PR을 하게 된 문제상황, 배경 및 개요에 대해서 작성해주세요!
>
> 퍼블리싱의 경우 스크린샷/동영상도 추가해주면 좋아요!
> PR에서 한 작업을 작성해주세요!
>
>

hotfix :: smsTryTime 초기화 문제
