src/main/java/team/startup/expo/domain/expo/presentation/ExpoController.java
src/main/java/team/startup/expo/domain/expo/service/DeleteExpoService.java
src/main/java/team/startup/expo/domain/expo/service/impl/DeleteExpoServiceImpl.java
src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/participant/repository/ParticipantRepository.java
src/main/java/team/startup/expo/domain/standard/StandardProgram.java
src/main/java/team/startup/expo/domain/standard/StandardProgramUser.java
src/main/java/team/startup/expo/domain/standard/repository/StandardProgramRepository.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java
src/main/java/team/startup/expo/domain/training/TrainingProgram.java
src/main/java/team/startup/expo/domain/training/TrainingProgramUser.java
src/main/java/team/startup/expo/domain/training/repository/TrainingProgramRepository.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 삭제와 삭제하는 동시에 관련된 연수 프로그램, 일반 프로그램, 연수자, 박람회 방문자 들을 동시에 삭제하는 로직을 추가하였습니다.
* DeleteExpo api 추가
* Expo와 관련된 엔티티 cascade 적용

🔀 :: 박람회 삭제

---

src/main/java/team/startup/expo/domain/attendance/exception/AlreadyEnterExpoUserException.java
src/main/java/team/startup/expo/domain/attendance/presentation/AttendanceController.java
src/main/java/team/startup/expo/domain/attendance/presentation/dto/request/PreEnterScanQrCodeRequestDto.java
src/main/java/team/startup/expo/domain/attendance/service/PreEnterScanQrCodeService.java
src/main/java/team/startup/expo/domain/attendance/service/impl/PreEnterScanQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회를 입장 하기 전 네임텍을 출력할 때 박람회에 출석여부를 판단하기 위해 추가하였습니다
Resolves: #77 
* PreEnterScanQrCode api 추가
* Trainee, ExpoParticipant에 attendanceStatus 추가
attendanceStatus를 추가하여 ERD가 수정되었습니다

🔀 :: 박람회 입장 전 출석 api

---

src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/presentation/dto/request/PreApplicationForParticipantRequestDto.java
src/main/java/team/startup/expo/domain/form/service/PreApplicationForParticipantService.java
src/main/java/team/startup/expo/domain/form/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/PreApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/trainee/ParticipationType.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

일반 참가자가 사전 신청을 할 수 있는 api를 추가하였습니다
Resolves: #97 
* PreApplicationForParticipant api 추가
원래 참가 상태를 나타내던 status를 삭제하고 attendanceStatus로 변경하여 가독성을 향샹시켰습니다.
또한, 사전과 현장을 나누기 위해 ParticipationType을 추가하여 나누었습니다.

🔀 :: 일반 참가자 사전 신청

---

src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/sms/service/impl/SendQrServiceImpl.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java

전에 id를 Long에서 ULID로 변경하면서 값이 길어져 QrCode를 저장할 때 byte[]로 저장시 너무 길어 저장이 안되는 문제가 발생하였습니다
그리하여 QrCode 컬럼이 필요하지 않다고 생각이 들어 삭제하였습니다
Resolves: #99 
* QrCode 컬럼 삭제

🔀 :: QrCode 저장 문제

---

src/main/java/team/startup/expo/domain/attendance/presentation/AttendanceController.java
src/main/java/team/startup/expo/domain/attendance/presentation/dto/response/PreEnterScanQrCodeResponseDto.java
src/main/java/team/startup/expo/domain/attendance/service/PreEnterScanQrCodeService.java
src/main/java/team/startup/expo/domain/attendance/service/impl/PreEnterScanQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/sms/service/impl/SendQrServiceImpl.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java

명찰에 넣어야될 값을 박람회 입장 전 찍는 qr에 반환값을 추가하여 정보를 반환하는 형식으로 변경하였습니다
Resolves: #101 
* PreEnterScanQrCode api 반환값 추가
전에 필요하지 않다고 삭제한 qrCode 컬럼을 다시 추가하였습니다

🔀 :: 명찰 출력 값 추가

---

src/main/java/team/startup/expo/domain/participant/presentation/ParticipantController.java
src/main/java/team/startup/expo/domain/participant/presentation/dto/response/GetParticipantInfoResponseDto.java
src/main/java/team/startup/expo/domain/participant/repository/ParticipantRepository.java
src/main/java/team/startup/expo/domain/participant/service/GetParticipantInfoService.java
src/main/java/team/startup/expo/domain/participant/service/impl/GetParticipantInfoServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

사전 신청과 현장 참가자의 정보를 출력하는 api를 추가하였습니다
Resolves: #105 
사전 신청과 현장 참가자를 ParticipationType으로 나누어 사전 신청과 현장 신청을 나누어 정보를 가져올 수 있도록 하였습니다.

🔀 :: 사전 신청 및 현장 참가자 정보 

---

src/main/java/team/startup/expo/domain/form/exception/AlreadyApplicationUserException.java
src/main/java/team/startup/expo/domain/form/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/PreApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/participant/ExpoParticipant.java
src/main/java/team/startup/expo/domain/participant/repository/ParticipantRepository.java
src/main/java/team/startup/expo/domain/trainee/Trainee.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java

만약 연수자와 일반 참가자의 동일인물이 존재할시 로직의 오류가 생겨 이를 방지하기 위해 if문을 추가하였습니다
Resolves: #109 
* 연수자 및 일반 참가자 중복 데이터 방지 if문 추가

🔀 :: 일반 참가자 및 연수자 중복 방지

---

src/main/java/team/startup/expo/domain/expo/service/impl/DeleteExpoServiceImpl.java

연수 프로그램 신청 연수자와 일반 프로그램의 일반 관람객을 삭제하지 않아 외래키 제약 조건이 발생하여 로직을 수정하였습니다
Resolves: #119 
* trainingProgramUser, standardProgramUser를 forEach를 사용하여 삭제 로직 추가
급하게 수정하느라 나중에 리팩토링 진행하겠습니다

🔀 :: 외래키 제약 조건 로직 수정

---

src/main/java/team/startup/expo/domain/attendance/presentation/AttendanceController.java
src/main/java/team/startup/expo/domain/attendance/service/PreEnterScanQrCodeService.java
src/main/java/team/startup/expo/domain/attendance/service/impl/PreEnterScanQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/participant/repository/ParticipantRepository.java
src/main/java/team/startup/expo/domain/sms/presentation/SmsController.java
src/main/java/team/startup/expo/domain/sms/service/SendQrService.java
src/main/java/team/startup/expo/domain/sms/service/impl/SendQrServiceImpl.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 다중 신청이 가능하게 되어 api에 존재하는 쿼리 메서드를 변경하였습니다
Resolves: #127 
* findByPhoneNumber -> findByPhoneNumberAndExpo
* Path로 ExpoId 추가 요청
>
>

🔀 :: 박람회 다중 신청에 대한 api 수정

---

src/main/java/team/startup/expo/domain/form/entity/DynamicForm.java
src/main/java/team/startup/expo/domain/form/exception/AlreadyExistFormException.java
src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/presentation/dto/request/CreateFormRequestDto.java
src/main/java/team/startup/expo/domain/form/repository/DynamicFormRepository.java
src/main/java/team/startup/expo/domain/form/repository/FormRepository.java
src/main/java/team/startup/expo/domain/form/service/CreateFormService.java
src/main/java/team/startup/expo/domain/form/service/impl/CreateFormServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

폼과 동적폼을 생성할 수 있는 api를 추가하였습니다
Resolves: #142 
* CreateForm api 추가
위 이미지는 폼 json의 형식 예시입니다.

🔀 :: 폼과 동적폼 생성

---

src/main/java/team/startup/expo/domain/expo/presentation/dto/request/GenerateExpoRequestDto.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/request/UpdateExpoRequestDto.java
src/main/java/team/startup/expo/domain/expo/service/impl/GenerateExpoServiceImpl.java
src/main/java/team/startup/expo/domain/expo/service/impl/UpdateExpoServiceImpl.java
src/main/java/team/startup/expo/domain/standard/presentation/dto/request/UpdateStandardProRequestDto.java
src/main/java/team/startup/expo/domain/training/presentation/dto/request/UpdateTrainingProRequestDto.java

박람회를 생성/수정을 하는 api에 연수/일반 프로그램을 추가하고 수정하는 api를 각각 로직에 더하여 한번에 처리하도록 수정하였습니다
* GenerateExpo api + Add(Standard/Training)Program api
* UpdateExpo api + Update(Standard/Training)Program api
아직 연수/일반 프로그램 추가 및 수정 api를 제거하지 않아 나중에 제거해야됩니다.

🔀 :: 박람회 생성/수정 및 연수/일반 프로그램 api 결합

---

src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/sms/event/SendQrEvent.java
src/main/java/team/startup/expo/domain/sms/event/handler/SendQrEventHandler.java

박람회 신청 후 Qr을 발송하는 과정에서 신청이 되지 않아도 QR이 발송되거나 다른 문제들이 발견되어 QR 전송을 이벤트로 만들어 신청이 정상적으로 되면 발송되게 처리하였습니다
Resolves: #166 
* SendQr을 ApplicationEvent로 만들어 비동기 처리
* application에 존재하는 모든 api에 동일하게 적용

🔀 :: 박람회 신청과 Qr 발송 이벤트 처리

---

src/main/java/team/startup/expo/domain/sms/service/impl/SendMessageServiceImpl.java

박람회 내에서 연수자와 참가자 문자 보내기 로직 중 박람회 내에 조회 했을 경우 존재하는지 검증하는 조건문에서 예외처리가 서로 바껴 잘못되어 있던 문제를 수정하였습니다
Resolves: #172 
* sendMessageForTrainee(Participant) if문 수정

🔀 :: 박람회 연수자 / 참가자 문자 보내기 예외처리 문제

---

src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/attendance/presentation/dto/response/PreEnterScanQrCodeResponseDto.java
src/main/java/team/startup/expo/domain/attendance/service/impl/PreEnterScanQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/attendance/service/impl/ScanStandardProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/attendance/service/impl/ScanTrainingProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/expo/exception/NotInProgressExpoException.java
src/main/java/team/startup/expo/domain/expo/service/impl/DeleteExpoServiceImpl.java
src/main/java/team/startup/expo/domain/participant/entity/StandardParticipant.java
src/main/java/team/startup/expo/domain/participant/entity/StandardParticipantParticipation.java
src/main/java/team/startup/expo/domain/participant/repository/StandardParticipantParticipationRepository.java
src/main/java/team/startup/expo/domain/participant/repository/StandardParticipantRepository.java
src/main/java/team/startup/expo/domain/participant/service/impl/GetParticipantInfoServiceImpl.java
src/main/java/team/startup/expo/domain/sms/event/handler/SendQrEventHandler.java
src/main/java/team/startup/expo/domain/sms/service/impl/SendMessageServiceImpl.java
src/main/java/team/startup/expo/domain/sms/service/impl/SendQrServiceImpl.java
src/main/java/team/startup/expo/domain/standard/service/impl/ApplicationStandardProListServiceImpl.java
src/main/java/team/startup/expo/domain/trainee/entity/Trainee.java
src/main/java/team/startup/expo/domain/trainee/entity/TraineeParticipation.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeParticipationRepository.java
src/main/java/team/startup/expo/global/date/DateUtil.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java

박람회가 이틀이상 진행하는 경우 StandardParticipant와 Trainee 테이블에서 관리하기에는 유연성이 떨어지기 때문에 테이블을 하나 더 생성하여 입장하는 경우 체크할 수 있도록 설정하였습니다
Resolves: #183 
* StandardParticipantParticipation 관련 로직 추가
* TraineeParticipation 관련 로직 추가
* 일반 프로그램 출석 N + 1 발생
* 연수 프로그램 출석 N + 1 발생

🔀 :: 박람회 출석 관련 테이블 분리 및 출석 로직 수정

---

src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/repository/FormRepository.java
src/main/java/team/startup/expo/domain/form/service/GetFormService.java
src/main/java/team/startup/expo/domain/form/service/impl/GetFormServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 신청폼을 불러오는 중에 Path를 formId로 설정하여 클라이언트가 알 수 있는 방법이 없어 expoId로 수정 후 파라미터를 추가로 받아 Trainee 혹은 Standard인지 받아 로직을 수정하였습니다
Resolves: #185 
* Path를 formId -> expoId로 변경
* Param으로 ParticipantType을 추가로 Request

🔀 :: 박람회 신청폼 불러오기 Path 수정

---

src/main/java/team/startup/expo/domain/participant/repository/StandardParticipantRepository.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java

연수자 / 일반 참가자 검색 api를 사용하면 이름을 모두 검색해야 결과가 뜨는 문제가 있어 LIKE를 사용하여 한글자로도 검색이 될 수 있도록 수정하였습니다.
Resolves: #189 
* TraineeRepository에서 findByExpoAndName에 JPQL을 사용하여 쿼리 조회
* StandardParticipantRepository에서 findByExpoAndApplicationTypeAndName에 JPQL을 사용하여 쿼리 조회

🔀 :: 연수자/일반 참가자 검색 api 기대한 검색결과 불일치 문제

---

src/main/java/team/startup/expo/domain/survey/entity/DynamicSurvey.java
src/main/java/team/startup/expo/domain/survey/entity/Survey.java
src/main/java/team/startup/expo/domain/survey/exception/AlreadyExistSurveyException.java
src/main/java/team/startup/expo/domain/survey/presentation/SurveyController.java
src/main/java/team/startup/expo/domain/survey/presentation/dto/request/SurveyRequestDto.java
src/main/java/team/startup/expo/domain/survey/repository/DynamicSurveyRepository.java
src/main/java/team/startup/expo/domain/survey/repository/SurveyRepository.java
src/main/java/team/startup/expo/domain/survey/service/CreateSurveyService.java
src/main/java/team/startup/expo/domain/survey/service/impl/CreateSurveyServiceImpl.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 참여 후 설문조사를 받기 위한 폼 생성 api를 추가하였습니다
Resolves: #195 
* CreateSurvey api 추가
* Survey 엔티티 Enum 저장 타입 정하기 위해 어노테이션 추가

🔀 :: 박람회 설문조사 생성 api

---

src/main/java/team/startup/expo/domain/survey/presentation/SurveyController.java
src/main/java/team/startup/expo/domain/survey/presentation/dto/response/SurveyResponseDto.java
src/main/java/team/startup/expo/domain/survey/repository/DynamicSurveyRepository.java
src/main/java/team/startup/expo/domain/survey/service/UpdateSurveyService.java
src/main/java/team/startup/expo/domain/survey/service/impl/UpdateSurveyServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 설문조사 폼 수정할 수 있는 api를 추가하였습니다
Resolves: #198 
* UpdateSurvey api 추가
수정하는 과정에서 하나하나 바꾸기 힘들어 DynamicSurvey에 존재하는 데이터를 지우고 추가하는 과정에서 총 8개의 쿼리가 보내져 나중에 최적화하는 편이 좋을 것 같습니다.

🔀 :: 박람회 설문조사 폼 수정

---

src/main/java/team/startup/expo/domain/survey/presentation/SurveyController.java
src/main/java/team/startup/expo/domain/survey/repository/SurveyRepository.java
src/main/java/team/startup/expo/domain/survey/service/DeleteSurveyService.java
src/main/java/team/startup/expo/domain/survey/service/impl/DeleteSurveyServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 설문조사 폼을 삭제할 수 있는 api를 추가하겠습니다
Resolves: #199 
* DeleteSurvey api 추가
박람회 설문조사에서 DynamicSurvey가 늘어날 수록 쿼리가 많아질 것으로 예상됩니다.
테스트에서 각각 일반과 연수를 나눠서 2개씩 데이터를 넣어 테스트한 결과 약 11개의 쿼리가 발생하였습니다.

🔀 :: 박람회 설문조사 삭제

---

src/main/java/team/startup/expo/domain/expo/entity/Expo.java
src/main/java/team/startup/expo/domain/expo/presentation/dto/request/UpdateExpoRequestDto.java
src/main/java/team/startup/expo/domain/expo/service/impl/DeleteExpoServiceImpl.java
src/main/java/team/startup/expo/domain/expo/service/impl/GenerateExpoServiceImpl.java
src/main/java/team/startup/expo/domain/expo/service/impl/UpdateExpoServiceImpl.java
src/main/java/team/startup/expo/domain/form/entity/DynamicForm.java
src/main/java/team/startup/expo/domain/form/entity/Form.java
src/main/java/team/startup/expo/domain/form/repository/FormRepository.java
src/main/java/team/startup/expo/domain/participant/entity/StandardParticipant.java
src/main/java/team/startup/expo/domain/participant/entity/StandardParticipantParticipation.java
src/main/java/team/startup/expo/domain/standard/entity/StandardProgram.java
src/main/java/team/startup/expo/domain/standard/entity/StandardProgramUser.java
src/main/java/team/startup/expo/domain/survey/answer/entity/StandardParticipantSurveyAnswer.java
src/main/java/team/startup/expo/domain/survey/answer/entity/TraineeSurveyAnswer.java
src/main/java/team/startup/expo/domain/survey/management/entity/DynamicSurvey.java
src/main/java/team/startup/expo/domain/survey/management/entity/Survey.java
src/main/java/team/startup/expo/domain/survey/management/repository/DynamicSurveyRepository.java
src/main/java/team/startup/expo/domain/survey/management/repository/SurveyRepository.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/DeleteSurveyServiceImpl.java
src/main/java/team/startup/expo/domain/trainee/entity/Trainee.java
src/main/java/team/startup/expo/domain/trainee/entity/TraineeParticipation.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeParticipationRepository.java
src/main/java/team/startup/expo/domain/training/entity/TrainingProgram.java
src/main/java/team/startup/expo/domain/training/entity/TrainingProgramUser.java
src/main/java/team/startup/expo/domain/training/service/impl/AddTrainingProServiceImpl.java

박람회 삭제를 초반에 만들어 뒤에 들어난 Expo와 연관관계가 있는 엔티티가 삭제되지 않아 외래키 제약조건이 발생하는 문제를 해결하였습니다.
Resolves: #205 
* JPQL으로 몇몇 쿼리 최적화
* DeleteExpo api 수정
테스트 시에 프로그램 일반/연수 2개씩과 프로그램 안에 참가자 2씩넣고 다른 데이터들도 2개씩 넣어 테스트결과 41개의 쿼리가 발생하였습니다.

🔀 :: 박람회 삭제 500 문제 해결

---

src/main/java/team/startup/expo/domain/attendance/service/impl/PreEnterScanQrCodeServiceImpl.java

박람회 입장 후 퇴장 시에 여러번 찍혀 퇴장시간이 바뀌는 상황이 있어 이미 퇴장하였다면 에러가 뜨게 핸들링하였습니다
Resolves: #211 
* 퇴장되었다면 에러가 뜨게 핸들링 처리

🔀 :: 박람회 입장 조건문 추가

---

src/main/java/team/startup/expo/domain/attendance/service/impl/ScanStandardProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/attendance/service/impl/ScanTrainingProByQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/standard/entity/StandardProgramUser.java
src/main/java/team/startup/expo/domain/training/entity/TrainingProgramUser.java

현재 로직에서 사전신청을 하지 않으면 프로그램 또는 행사가 참가되지 않는 로직이였지만 현장에서도 바로 참가할 수 있도록 변경하였습니다
* QR인식 후 프로그램 참가하는 로직에서 만약 사전신청을 하지 않았다면 엔티티를 그 즉시 생성하여 참여할 수 있도록 수정

🔀 :: 박람회 현장 참가

---

src/main/java/team/startup/expo/domain/expo/service/impl/UpdateExpoServiceImpl.java

박람회를 수정하며 로직에서 프로그램을 해당 id로 찾아 수정하는 로직이였지만 그렇게 수정한다면 원래 있던것은 수정이 되지만 새로 추가하며 id가 바껴 올바르게 수정되지 않는 문제를 해결하였습니다
Resolves: #229 
* 프로그램을 하나하나씩 하는 것이 아닌 해당 Expo로 연관관계 매핑되어 있는 엔티티를 찾아 삭제 후 새로 추가하는 방식으로 수정하였습니다

🔀 :: 박람회 수정이 올바르게 진행되지 않는 문제

---

src/main/java/team/startup/expo/ExpoApplication.java
src/main/java/team/startup/expo/domain/sms/event/handler/SendQrEventHandler.java

sms 문자를 발송하는 과정에서 ApplicationEvent를 사용하여 동기적으로 처리하는데 많은 사람들이 동시에 박람회 신청을 하게 된다면 동기적으로 처리하는 것보다 비동기로 처리하는 것이 효율적이라고 생각이 들어 비동기로 변경하였습니다
Resolves: #233 
* sendQrHandler Async 처리

🔀 :: sms 문자 발송 비동기 설정

---

src/main/java/team/startup/expo/domain/form/presentation/FormController.java
src/main/java/team/startup/expo/domain/form/service/DeleteFormService.java
src/main/java/team/startup/expo/domain/form/service/UpdateFormService.java
src/main/java/team/startup/expo/domain/form/service/impl/DeleteFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/UpdateFormServiceImpl.java
src/main/java/team/startup/expo/domain/survey/management/presentation/SurveyController.java
src/main/java/team/startup/expo/domain/survey/management/repository/DynamicSurveyRepository.java
src/main/java/team/startup/expo/domain/survey/management/service/DeleteSurveyService.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/DeleteSurveyServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

form과 survey의 Update와 Delete api에서 participationType을 추가로 받아 특정 엔티티만 삭제또는 수정할 수 있도록 변경하였습니다
Resolves: #235 
* form update Path 변경 : formId -> expoId
* form Delete Path 추가 : `/{expo_id}` -> `/{expo_id}/{participationType}`
* survey Delete Path 추가 : `/{expo_id}` -> `/{expo_id}/{participationType}`

🔀 :: form 및 survey Path 변경

---

src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/sms/event/handler/SendQrEventHandler.java

sms에서 비동기 통신을 하는 중에 비동기 통신에서 반환값이 정상적으로 반환되지 않는 문제를 비동기에서 반환가능한 클래스안 `CompletableFuture` 감싸 반환하는 방식으로 문제를 해결하였습니다.
Resolves: #238 
* SendQrEventHandler의 메서드 반환값 수정

🔀 :: sms 비동기 통신 중 발생하는 문제 

---

src/main/java/team/startup/expo/ExpoApplication.java
src/main/java/team/startup/expo/domain/form/presentation/dto/response/GetFormResponseDto.java
src/main/java/team/startup/expo/domain/form/service/impl/DeleteFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/GetFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/UpdateFormServiceImpl.java
src/main/java/team/startup/expo/global/redis/RedisConfig.java

일반 관람객 사전/현장 신청에 필요한 폼을 불러오는 응답을 Redis를 이용해 캐싱하여 성능개선하였습니다.
Resolves: #244 
* cacheManager 설정
* API 캐싱 및 동기화 설정
**테스트 시 레이턴시 약 95%감소

🔀 :: 일반 관람객 사전/현장 신청 폼 불러오기 API 캐싱

---

src/main/java/team/startup/expo/domain/form/service/impl/DeleteFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/GetFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/UpdateFormServiceImpl.java
src/main/java/team/startup/expo/domain/survey/management/presentation/dto/response/SurveyResponseDto.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/DeleteSurveyServiceImpl.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/GetSurveyServiceImpl.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/UpdateSurveyServiceImpl.java
src/main/java/team/startup/expo/global/redis/RedisConfig.java

설문조사 관련 API들을 Redis를 사용하여 Cache를 적용하였습니다.
Resolves: #245 
* 설문조사 삭제/ 수정 CacheEvict 적용
* 설문조사 불러오기 CacheEvict 적용
레이턴시 약 93% 감소하였습니다
Look Aside + Write Around 조합을 사용하여 구현하였습니다

🔀 :: 설문조사 관련 RedisCache 적용

---

src/main/java/team/startup/expo/domain/participant/entity/StandardParticipant.java
src/main/java/team/startup/expo/domain/sms/event/handler/SendQrEventHandler.java
src/main/java/team/startup/expo/domain/sms/service/impl/SendQrServiceImpl.java
src/main/java/team/startup/expo/domain/trainee/entity/Trainee.java

QR을 저장하는 과정에서 DB에서 너무 많은 용량을 차지하여 비정상적으로 DB 용량이 늘어나는 문제가 발생하였고 저장 후 사용하는 로직이 없어 삭제하였습니다
Resolves: #249 
* StandardParticipant and Trainee QR 컬럼 삭제 및 관련 로직 삭제

🔀 :: QR 컬럼 및 로직 삭제

---

src/main/java/team/startup/expo/domain/stat/presentation/StatController.java
src/main/java/team/startup/expo/domain/stat/presentation/dto/response/StandardParticipantStatsResponse.java
src/main/java/team/startup/expo/domain/stat/service/GetStandardStatsService.java
src/main/java/team/startup/expo/domain/stat/service/impl/GetStandardStatsServiceImpl.java
src/main/java/team/startup/expo/global/security/config/SecurityConfig.java

박람회 참가자 통계 그래프에 대한 정보를 반환하는 API를 개발하였습니다
Resolves: #252 
* getStandardStats API 추가
percent의 합계가 100으로 나오지 않는 문제를 반올림처리하여 100으로 나오도록 하였습니다

🔀 :: 박람회 참가자 통계 그래프 수치 API

---

src/main/java/team/startup/expo/domain/form/entity/Form.java
src/main/java/team/startup/expo/domain/form/presentation/dto/request/FormRequestDto.java
src/main/java/team/startup/expo/domain/form/presentation/dto/response/GetFormResponseDto.java
src/main/java/team/startup/expo/domain/form/service/impl/CreateFormServiceImpl.java
src/main/java/team/startup/expo/domain/form/service/impl/GetFormServiceImpl.java
src/main/java/team/startup/expo/domain/survey/management/entity/Survey.java
src/main/java/team/startup/expo/domain/survey/management/presentation/dto/request/SurveyRequestDto.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/CreateSurveyServiceImpl.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/UpdateSurveyServiceImpl.java

개인정보동의관련 문장을 이미지가 아닌 텍스트로 직접 입력하여 하는 방식으로 바뀌어 수정하였습니다
Resolves: #255 
* informationImage -> informationText 폼 엔티티 변경
* informationText 설문조사 추가
>
>

🔀 :: 폼 개인정보동의 이미지에서 텍스트로 변경

---

src/main/java/team/startup/expo/domain/application/presentation/ApplicationController.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForTraineeServiceImpl.java
src/main/java/team/startup/expo/domain/participant/repository/StandardParticipantRepository.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeRepository.java

박람회 사전/현장 신청 API에서 row lock을 적용하였습니다.
Resolves: #257 
해당 expo에서 trainee, standardParticipant 가 전화번호와 같은 것이 있는지 검증 후 save하기 전 row lock을 걸어 쿼리를 날리고 저장하게 하였습니다
trainee 혹은 standardParticipant에서 쿼리를 같이 exist를 날리지 않으면 최적화가 가능할 것 같습니다. 추후 확인 후 변경하겠습니다

🔀 :: 박람회 사전/현장 신청 row lock 적용

---

src/main/java/team/startup/expo/domain/attendance/entity/LeaveManager.java
src/main/java/team/startup/expo/domain/attendance/exception/NotEnterAfterThirtySecondException.java
src/main/java/team/startup/expo/domain/attendance/repository/LeaveManagerRepository.java
src/main/java/team/startup/expo/domain/attendance/service/impl/PreEnterScanQrCodeServiceImpl.java
src/main/java/team/startup/expo/domain/form/entity/ParticipationType.java
src/main/java/team/startup/expo/domain/participant/repository/StandardParticipantParticipationRepository.java
src/main/java/team/startup/expo/domain/trainee/repository/TraineeParticipationRepository.java
src/main/java/team/startup/expo/global/exception/ErrorCode.java

박람회를 입장 한 시점에서 30초 이후부터 퇴장이 가능하도록 redis를 이용하여 구현하였고 Participation 엔티티들을 조회할 때 row lock을 걸어 동시성 문제가 터지지 않도록 하였습니다.
Resolves: #260 
* findByExpoAndTraineeAndAttendanceDateForWrite method row lock confirm
* findByExpoAndStandardParticipantAndAttendanceDateForWrite method row lock confirm
* 

🔀 :: 박람회 입장/퇴장 30초 이후 가능하게 적용 및 row lock 적용

---

src/main/java/team/startup/expo/domain/participant/presentation/ParticipantController.java
src/main/java/team/startup/expo/domain/participant/repository/custom/impl/ParticipantCustomRepositoryImpl.java
src/main/java/team/startup/expo/domain/participant/service/impl/GetParticipantInfoServiceImpl.java

참가자를 불러올 때 페이징의 정보가 잘못되어 정상적으로 불러와지지 않는 문제를 해결하였습니다.
Resolves: 
* searchParticipants 로직 변경
totalElement를 초기화 할 때 기존의 방식으로 초기화가 되지 않아 query를 날려 count를 넣어 초기화하는 방식으로 변경하였습니다.

🔀 :: 참가자 불러오기 페이징 문제

---

src/main/java/team/startup/expo/domain/excel/service/impl/StandardParticipantInfoToExcelServiceImpl.java
src/main/java/team/startup/expo/domain/survey/answer/repository/StandardParticipantSurveyAnswerRepository.java

참가자의 정보를 엑셀로 출력하는 동시에 만족도 조사를 완료하면 같이 엑셀 출력이 가능하도록 하였습니다.
* standardParticipantInfoToExcel 에 만족도 조사 결과 추가 반환
>
>

🔀 :: 참가자 정보 엑셀 출력 및 만족도 조사 결과 동시 출력

---

src/main/java/team/startup/expo/domain/survey/answer/entity/Draw.java
src/main/java/team/startup/expo/domain/survey/answer/presentation/SurveyAnswerController.java
src/main/java/team/startup/expo/domain/survey/answer/presentation/dto/response/StandardSurveyAnswerResponseDto.java
src/main/java/team/startup/expo/domain/survey/answer/repository/StandardParticipantSurveyAnswerRepository.java
src/main/java/team/startup/expo/domain/survey/answer/service/StandardSurveyAnswerService.java
src/main/java/team/startup/expo/domain/survey/answer/service/impl/StandardSurveyAnswerServiceImpl.java
src/main/java/team/startup/expo/domain/survey/management/entity/Survey.java
src/main/java/team/startup/expo/domain/survey/management/repository/SurveyRepository.java
src/main/java/team/startup/expo/domain/survey/management/service/impl/CreateSurveyServiceImpl.java

설문조사 완료시 행운의 숫자 당첨 여부를 반환할 수 있게 로직을 추가하였습니다.
* Survey에 totalAnswers 추가
* Draw Enum 추가
* 일반 참가자 설문조사 참여 후 당첨 여부 반환 로직 추가
>
>

🔀 :: 설문조사 완료시 행운의 숫자 당첨 여부 반환

---

src/main/java/team/startup/expo/domain/alarm/presentation/AlarmController.java
src/main/java/team/startup/expo/domain/alarm/service/SaveYesterdayPersonService.java
src/main/java/team/startup/expo/domain/alarm/service/SendParticipantNumberByExpoService.java
src/main/java/team/startup/expo/domain/alarm/service/impl/SaveYesterdayPersonServiceImpl.java
src/main/java/team/startup/expo/domain/alarm/service/impl/SendParticipantNumberByExpoServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationTemporaryQrServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/expo/entity/Expo.java
src/main/java/team/startup/expo/global/thirdparty/discord/properties/DiscordProperties.java
src/main/resources/application.yml

하루마다 스케줄러를 작동시켜 박람회별 등록자 수 통계를 디스코드로 전송하는 스케줄러를 추가하였습니다
Resolves: 
* 8시, 12시,16시,20시 마다 박람회 등록자 수 통계를 보내는 스케줄러 추가
* 0시에 총 등록자 수를 어제 등록자 수로 저장하는 스케줄러 추가
>
>

🔀 :: 박람회별 등록자 수 통계 알림

---

src/main/java/team/startup/expo/domain/application/event/handler/SendQrEventHandler.java
src/main/java/team/startup/expo/domain/application/service/impl/FieldApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/application/service/impl/PreApplicationForParticipantServiceImpl.java
src/main/java/team/startup/expo/domain/participant/entity/StandardParticipant.java
src/main/java/team/startup/expo/domain/participant/repository/StandardParticipantRepository.java

등록시 SMS 한번만 발송되지만 만약 문자를 받지 못한 것을 대비해 최대 2번 발송되도록 하였습니다.
* smsTryTime 컬럼 추가
* findByPhoneNumberAndExpoForNullCheck JPQL 쿼리 추가
>
>

🔀  :: 박람회 등록 최대 2회로 수정
